// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "apiBase": string;
      "apiKey": string;
      "model": string;
      "temperature": number;
      "enableThoughts": boolean;
      "thinkingBudget": number;
      "concurrency": number;
      "maxChars": number;
      "attachmentFilter": string;
      "prompt": string;
    };
  }
}
